{% set version = "0.3-3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-speedglm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://cran.r-project.org/src/contrib/speedglm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/speedglm/speedglm_{{ version }}.tar.gz
  sha256: d065d0ee42fb772760fca8d97ad2aa56cd76b1d9ecb4e97478ec362429e16738

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-mass
    - r-matrix

  run:
    - r-base
    - r-mass
    - r-matrix

test:
  commands:
    - $R -e "library('speedglm')"  # [not win]
    - "\"%R%\" -e \"library('speedglm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=speedglm
  license: GPL
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  summary: Fitting linear models and generalized linear models to large data sets by updating algorithms.
  license_family: GPL

extra:
  recipe-maintainers:
    - conda-forge/r
