{% set version = "0.3-5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-speedglm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/speedglm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/speedglm/speedglm_{{ version }}.tar.gz
  sha256: f8663677c10ff324c5639402060ddd2b1a1e917445cb0f8f84e146b85e82bb4b

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-biglm
    - r-mass
    - r-matrix
  run:
    - r-base
    - r-biglm
    - r-mass
    - r-matrix

test:
  commands:
    - $R -e "library('speedglm')"           # [not win]
    - "\"%R%\" -e \"library('speedglm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=speedglm
  license: GPL-2.0-or-later
  summary: Fitting linear models and generalized linear models to large data sets by updating algorithms.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
