travis:
  secure:
    BINSTAR_TOKEN: syXDdzV5Yueirq+lB3U7fwksXlfq5gOldHEjbdNBKn1v/601LFhs5CUvhOSF9hnbHQELHY7dS6MZAfYHyw0t3SpcLJ+5p0N+hl9/EuOi8Vm3M4APLzJUXW/CTtB86NRKR3fRy9y9KFy7gEgYsIa05hH+W49T8iMDI4DtZd/Q7d0Sjiz9VRcXLGIdoHHvi2a+j+iOyebELCAfgIokFVhxSbQqQ+ml2/AYBRrZEuc+OgrZr4abwGBMwn2KPaGSYoDvfugnIS0PhcDroJVZDeT0akVggTn9kPgVDnW1vp5csmg1uZKuCusTMhGAOoLASYJOnAEs9Cv0G1n5c8vG8Guz36ZNhS7CoGVAjWCEk38NKCyWkyuJhjvM99n445WUZMoNhDmVG//aatkLgUsxRMsBrPJ5Mkzk3wWwVXtxfzSnt/fsfvtsLF12/aWGje+ggXoRgjA6cEuOlLGdnlesGHYFwsxFTcf546T+IqB8WT1ttY5oJNG98YwyiIEvC6TxYn6KRInjRuWIpXTZsyTo9ogbd4HNncZ/Qh2WOfBOvkN1vu5G0QO2OMQeSfjfvcUoaoh96OD3aOy5SnG4LxhH0iN/3/MXHP2+zUUCqqFrd+M/PxFt8DKUbZnku/kzX9qqRCtpGtG3xEPTExCnHMK+c0fTI+tQT6gActzFhVBqqLL7qTo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
