appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: vPTtVKnljVerI7fuTBiFS/9yAxEg6i4sKs9UvAw7E4QntK8MysEPbuU3V8TJHELFwTaIgogwwCHGOKgktPRHN6BKlARuWJ3ESkYbSivuMWhlSHI5fIqKxyp4AY7L+wktVmuX61TlxMpuiDMkAtPMCk8brHU+6EVCsU0PCybKDfDdz0o2Lq1l2qpKA7jvnenhhKpxC4HNqnLDOePDkWt4NfXPtCHnu6SynBauoVmKZq94kzi95NikK/FROQDsJjkuCUGd8EJhG+1zLAbal3sWUfElOGNWhFFxVfXILCreJz65AEoOzERSgOxxvsNOg///sdBZ+lgoEM6j+8omOMJTbnWsWvCqw1DjBjq7vQeIfiqFInoGeag+t/MMxhKF1V05gCNnhtxuepw2rPwjb56lMYbBnDmTmmWOd16fgMWtu1O4DThpJYZdtdZLn9Z8grciZLek9Tdymv0kE5/kb4+31FAvHrgUvb6YOX+yAXJCAZ2mp9gOg/XVSrNl8H9btT8zfB2+hWN99gsZpKWBcyl+lq2FmWKX7Wd3oXeEG7R6yfmiXLKX8bTl+Pu5OaMl/eXk4v/QXwTC8P3pBeh07wRIPqLZEb+kz1PHrQ8Mho1YuyASo4zy6AtMGDcmL28iqc2kj2FpAr0+zYgt7GEg6jXzS1Bff/pxXTVc3PVtGCGcQbo=
